[build-system]
requires = [
    "setuptools>=42", 
    "wheel", 
    "setuptools_scm[toml]>=6",
    "pip>=21.1.2"
]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/coco2customvision/_dist_ver.py"
write_to_template = "__version__ = '{version}'\n"